version: '3'
services:
  node-0.example.com:
    image: opensearchproject/opensearch:2.2.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=node-0.example.com
      - discovery.seed_hosts=node-0.example.com
      - cluster.initial_master_nodes=node-0.example.com
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    restart: always
    networks:
      - opensearch-net
    volumes:
      - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./certs/esnode.pem:/usr/share/opensearch/config/esnode.pem
      - ./certs/esnode-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ./certs/kirk.pem:/usr/share/opensearch/config/kirk.pem
      - ./certs/kirk-key.pem:/usr/share/opensearch/config/kirk-key.pem
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./config/opensearch-security/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - ./config/opensearch-security/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ./config/opensearch-security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
  node-1.example.com:
    image: opensearchproject/opensearch:2.2.0
    environment:
      - cluster.name=opensearch-cluster
      - node.name=node-1.example.com
      - discovery.seed_hosts=node-0.example.com,node-1.example.com
      - cluster.initial_master_nodes=node-0.example.com,node-1.example.com
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    networks:
      - opensearch-net
    volumes:
      - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./certs/esnode.pem:/usr/share/opensearch/config/esnode.pem
      - ./certs/esnode-key.pem:/usr/share/opensearch/config/esnode-key.pem
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      - ./config/opensearch-security/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml
      - ./config/opensearch-security/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml
      - ./config/opensearch-security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.2.0
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://node-0.example.com:9200"]'
    networks:
      - opensearch-net
    volumes:
      - ./certs/kirk.crt:/usr/share/opensearch-dashboards/config/kirk.crt
      - ./certs/kirk-key.pem:/usr/share/opensearch-dashboards/config/kirk-key.pem
      - ./certs/esnode.crt:/usr/share/opensearch-dashboards/config/esnode.crt
      - ./certs/esnode-key.pem:/usr/share/opensearch-dashboards/config/esnode-key.pem
      - ./certs/root-ca.pem:/usr/share/opensearch-dashboards/config/root-ca.pem
      - ./config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
  openldap:
    image: osixia/openldap
    container_name: openldap
    command: --copy-service # seemingly required to load directory.ldif
    ports:
      - 389:389
      - 636:636
    environment:
      - LDAP_ADMIN_PASSWORD=changethis
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=changethistoo
    volumes:
      - ./config/directory.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/directory.ldif
    networks:
      - opensearch-net
  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap
    networks:
      - opensearch-net


networks:
  opensearch-net:
# cn=Craig Perkins,cn=OpenSearch Users,dc=example,dc=org